### ISSUE TITLE
JS PARSING

### ISSUE THREAD

**Issue by John4064** [RCSIndustries/Project-Generator#20]
A. Could you take a look at the server and tell me what is needed priority wise as well as what is done wrong from a front end perspective.
B. Best Practice in JS Should I wrap and parse the api response to a data structure class or leave as json when I return the json response for you to use. (Currently it returns just the json string of the table)
C.  Should I have developed this all in Typescript from the start for performance as well as maintenance reasons? As I know you recommended Typescript previously. 
D. Any Specific Methods that arent already listed can you think that would be needed for core functionality?(Working on Post add and delete atm)
E. Message me for .env if you need to run the api at all as one is required in the server directory to connect to db.

Sorry it is a lot I meant to ask you these over the last week no worry if it takes you awhile to respond.

**Comment by John4064** [comment]
Forgot to add
F: if i wanted to create a logs type table is there any data in your experience that would be helpful in including

**Comment by John4064** [comment]
Do we setup auth or just have them enter their username into a field and anyone could search up their generated history?

**Comment by mattdimegs** [comment]
Auth for sure. Especially if we are doing a DB we can just have a user DB in there as well. I can do the coding for it but you just gotta do the encryption part for passing user and pass I suck at that.
